<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CmsPage;

class CmsPagesSeeder extends Seeder
{
    public function run(): void
    {
        CmsPage::updateOrCreate(['slug' => 'privacy-policy'], [
            'title'           => 'Privacy Policy',
            'last_updated_at' => now(),
            'content'         => '
<p style="font-size:1.05rem;font-weight:500;color:#334155;">
    At ' . config('app.name', 'Unjamm') . ', we take your privacy and the security of your financial data incredibly seriously. This policy outlines how we handle the sensitive information required to generate your disputes.
</p>

<hr style="border:none;border-top:1px solid #f1f5f9;margin:32px 0;">

<h2>1. Information We Collect</h2>
<p>To provide our dispute resolution services, we collect personal information including your name, email address, and specific details regarding your disputes. This includes transaction dates, disputed amounts, reference numbers, and the names of involved institutions.</p>

<h2>2. How We Use Your Data &amp; AI</h2>
<p>Your data is strictly used to facilitate the dispute process:</p>
<ul>
  <li><strong>AI Generation:</strong> We use your context to generate accurate legal and dispute templates. Your specific personal identifiers are anonymized where possible before being processed by our language models.</li>
  <li><strong>Workflow Tracking:</strong> Updating your case status and organizing your timeline.</li>
  <li><strong>Communication:</strong> Sending you critical system notifications.</li>
</ul>

<h2>3. Bank-Grade Security</h2>
<p>We employ bank-grade encryption to protect your sensitive records and dispute attachments. Your data is encrypted both in transit (via SSL/TLS) and at rest within our secure databases.</p>

<h2>4. Third-Party Services</h2>
<p>We use trusted third-party services to securely operate our platform. We share only the necessary information required for these services to function:</p>
<ul>
  <li><strong>Stripe:</strong> Used for secure payment processing. We do not store your full credit card information on our servers; it is handled entirely by Stripe.</li>
  <li><strong>SendGrid:</strong> Used for reliable email delivery, routing system notifications, and sending dispute communications.</li>
</ul>

<h2>5. Data Retention</h2>
<p>We retain your case files and attachments only for as long as necessary to resolve your dispute. Once a case is permanently closed, you maintain the right to request a complete deletion of your records from our active servers.</p>

<div style="margin-top:48px;padding:24px;background:#eff6ff;border-radius:12px;border:1px solid #dbeafe;">
  <h3 style="font-weight:700;color:#1e3a8a;margin-bottom:8px;">Contact our Privacy Team</h3>
  <p style="font-size:0.875rem;color:#1e40af;">
    If you have questions about this policy or wish to exercise your data rights, please contact us at
    <a href="mailto:' . config('app.admin_email') . '" style="font-weight:700;text-decoration:underline;">' . config('app.admin_email') . '</a>.
  </p>
</div>
',
        ]);

        CmsPage::updateOrCreate(['slug' => 'terms-of-service'], [
            'title'           => 'Terms of Service',
            'last_updated_at' => now(),
            'content'         => '
<p style="font-size:1.05rem;font-weight:500;color:#334155;">
    By creating an account and using ' . config('app.name', 'Unjamm') . ', you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.
</p>

<hr style="border:none;border-top:1px solid #f1f5f9;margin:32px 0;">

<div style="background:#fffbeb;border-left:4px solid #f59e0b;padding:20px 24px;border-radius:0 12px 12px 0;margin-bottom:32px;">
  <h3 style="font-weight:700;color:#78350f;margin-bottom:8px;">⚠ Platform Disclaimer &amp; Not Legal Advice</h3>
  <p style="font-size:0.875rem;color:#92400e;">
    ' . config('app.name', 'Unjamm') . ' is a technology platform that helps users organize and send dispute communications. It does not provide legal advice and does not guarantee dispute outcomes. The letters, templates, and workflows generated by our platform are for informational and organizational purposes only.
  </p>
</div>

<h2>1. User Responsibilities</h2>
<p>You are entirely responsible for the accuracy of the information you provide in your dispute cases. <strong>Users are also strictly responsible for reviewing all emails and communications generated by the platform before they are sent.</strong> Submitting fraudulent claims, falsifying documents, or utilizing our systems to harass institutions violates these terms and will result in immediate account termination.</p>

<h2>2. Dispute Outcomes</h2>
<p>' . config('app.name', 'Unjamm') . ' makes no guarantees regarding the outcome, timeframe, or financial recovery of your specific case. Each dispute is subject to the policies of the receiving institution.</p>

<h2>3. Fair Use</h2>
<p>Our AI generation tools and email delivery systems are subject to fair use. Automated scraping, reverse engineering, or attempting to bypass our rate limits is strictly prohibited.</p>

<h2>4. Account Termination</h2>
<p>We reserve the right to suspend or terminate your access to the platform at our sole discretion, without notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties.</p>
',
        ]);
    }
}
