@php
    $laws = [
        'EU' => 'Regulation (EC) No 261/2004',
        'UK' => 'UK261 (Regulation (EC) No 261/2004 as retained in UK law)',
        'CA' => "Canada's Air Passenger Protection Regulations (SOR/2019-150)",
        'US' => 'US Department of Transportation rules (14 CFR Parts 250 and 260)',
    ];
@endphp
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1e293b; line-height: 1.6; margin: 40px 50px; }
    h1 { font-size: 19px; margin: 0 0 2px; }
    .muted { color: #64748b; font-size: 11px; }
    .box { border: 1px solid #cbd5e1; border-radius: 6px; padding: 12px 16px; margin: 16px 0; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 3px 0; vertical-align: top; }
    td.k { color: #64748b; width: 170px; }
    .sig { margin-top: 40px; }
    .sig-box { border: 1px solid #cbd5e1; border-radius: 8px; background: #ffffff; padding: 14px 18px; margin-top: 10px; }
    .sig-label { font-size: 13px; font-weight: bold; color: #0f172a; }
    .sig-area { height: 90px; margin-top: 8px; border-bottom: 2px solid #1e293b; }
    .sig-area img { max-height: 84px; }
    ol li { margin-bottom: 6px; }
    .footer { margin-top: 36px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; }
</style>
</head>
<body>
    <h1>Assignment of Claims</h1>
    <div class="muted">Claim reference {{ $claim->reference }} - Claim No. {{ $claim->number }} - Jurisdiction: {{ $jurisdiction }}</div>

    <div class="box">
        <table>
            <tr><td class="k">Assignor (passenger(s))</td><td>{{ implode(', ', $passengers) }}</td></tr>
            <tr><td class="k">Assignee</td><td>Unjamm</td></tr>
            <tr><td class="k">Flight</td><td>{{ $claim->airline ?: '-' }} {{ $claim->flight_number ?: '' }} on {{ $claim->flight_date?->format('d F Y') ?: '-' }}</td></tr>
            <tr><td class="k">Route</td><td>{{ $claim->departure_airport }} to {{ $claim->arrival_airport }}</td></tr>
            @if ($claim->eligibility_regulation)
            <tr><td class="k">Legal basis</td><td>{{ $claim->eligibility_regulation }} {{ $claim->eligibility_article }}</td></tr>
            @endif
        </table>
    </div>

    <p>The Assignor assigns to the Assignee the claim for compensation arising from the disruption of the flight identified above under {{ $laws[$jurisdiction] ?? $laws['EU'] }}, for the purpose of enforcement and collection, on the following terms:</p>

    <ol>
        <li>The Assignee pursues the claim at its own cost and risk. If the claim is unsuccessful, the Assignor owes nothing.</li>
        <li>On successful settlement, the Assignee remits the recovered compensation to the Assignor after deducting the agreed success fee.</li>
        <li>The Assignor confirms the claim has not been assigned to any other party and no other party is pursuing it on their behalf.</li>
        <li>The Assignor may revoke this assignment in writing at any time before the claim is submitted to the carrier.</li>
    </ol>

    <div class="sig">
        <div class="sig-box">
            <div class="sig-label" style="text-transform: uppercase; letter-spacing: .05em; color: #64748b; font-size: 10px;">Authorised signature</div>
            <div class="sig-area">
                @if ($signature)
                    <img src="{{ $signature }}" alt="Signature">
                @else
                    {{-- Dropbox Sign text tag: becomes the guided signature field; white so it never shows in print --}}
                    <span style="color:#ffffff; font-size:34px;">[sig|req|signer1]</span>
                @endif
            </div>
            <div class="muted" style="margin-top:6px;">
                {{ $lead?->name ?? $passengers[0] ?? '' }}
                @if ($lead?->signed_at) - signed {{ $lead->signed_at->format('d F Y H:i') }} (UTC)@endif
            </div>
        </div>
    </div>

    <div class="footer">Generated by Unjamm on {{ now()->format('d F Y') }} - claim {{ $claim->reference }}</div>
</body>
</html>
